name: TF Cloud discard execution
on:
  workflow_dispatch:
    inputs:
      WORKSPACE:
        description: "Workspace name"
        required: true
        default: uux0vy-dev

jobs:
  deploy:
    name: Discard latest job
    runs-on: ubuntu-20.04
    steps:
      - name: Discard latest job
        run: >
          curl \
            -H "Authorization: Bearer ${{ secrets.TFC_TEAM_TOKEN }}" \
            -X GET \
            https://app.terraform.io/api/v2/organizations/bcgov/workspaces/${{ github.event.inputs.WORKSPACE }} \
            | jq -r '.data.relationships."current-run".data.id' \
            | xargs -I{} \
            curl -H "Authorization: Bearer ${{ secrets.TFC_TEAM_TOKEN }}" \
            -H "Content-Type: application/vnd.api+json" \
            -X POST \
            https://app.terraform.io/api/v2/runs/{}/actions/discard
